<template>
    <div>
        <div class="header">
            <div>路由笔记</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
            <div>首页</div>
        </div>
    </div>
</template>
<script>
export default {
  name: "Home"
};
</script>
<style lang="stylus" scoped>
</style>
