{
    "extConfig": [{
        "title": "标准名称",
        "formItems": [{
            "label": "标准英文",
            "value": "EN_NAME",
            "editer": "input",
            "placeholder": "标准英文"
        }, {
            "isExt": "true",
            "tag": "COL_EN_NAME",
            "tagName": "字段名称",
            "group": "1",
            "groupTitle": "标准名称",
            "tagType": "input",
            "dimCode": "",
            "fieldName": "",
            "fieldType": "",
            "isShow": "true",
            "sort": "2",
            "label": "字段名称",
            "editer": "input",
            "value": "COL_EN_NAME",
            "placeholder": "字段名称"
        }, {
            "label": "字段类型",
            "value": "COL_TYPE",
            "editer": "input",
            "placeholder": "字段类型"
        }, {
            "label": "标准别名",
            "value": "ALIAS",
            "editer": "input",
            "placeholder": "标准别名"
        }]
    }, {
        "title": "数据格式",
        "formItems": [{
            "label": "取值范围",
            "value": "DATA_VAL_AREA",
            "editer": "input",
            "placeholder": "取值范围"
        }, {
            "label": "数据长度",
            "value": "DATA_LENGTH",
            "editer": "input",
            "placeholder": "数据长度"
        }, {
            "label": "数据精度",
            "value": "DATA_PRECISION",
            "editer": "input",
            "placeholder": "数据精度"
        }, {
            "label": "度量单位",
            "value": "DATA_UNIT",
            "editer": "select",
            "dimCode": "DIM_ZB_UNIT",
            "placeholder": "度量单位"
        }]
    }, {
        "title": "标准质量",
        "formItems": [{
            "isExt": "false",
            "tag": "EXT_PRO1",
            "tagName": "定制化属性",
            "group": "3",
            "groupTitle": "标准管理",
            "tagType": "input",
            "dimCode": "",
            "fieldName": "",
            "fieldType": "",
            "isShow": "true",
            "sort": "1",
            "label": "定制化属性",
            "editer": "input",
            "value": "EXT_PRO1",
            "placeholder": "定制化属性"
        }, {
            "label": "编码规则",
            "value": "CODE_RULE",
            "editer": "input",
            "placeholder": "编码规则"
        }]
    }, {
        "title": "标准管理",
        "formItems": [{
            "label": "权威系统",
            "value": "AUTH_SYSTEM",
            "editer": "select",
            "dimCode": "DQ_AUTH_SYSTEM",
            "placeholder": "权威系统"
        }, {
            "label": "归口部门",
            "value": "REL_DEPT",
            "editer": "select",
            "dimCode": "DQ_OWNER_DEPT",
            "placeholder": "归口部门"
        }, {
            "label": "制度依据",
            "value": "MAKE_BASIS",
            "editer": "input",
            "placeholder": "制度依据"
        }, {
            "label": "版本",
            "value": "VERSEQ",
            "editer": "input",
            "placeholder": "版本",
            "disabled": true
        }]
    }, {
        "title": "定制化管理",
        "formItems": [{
            "isExt": "false",
            "tag": "EXT_PRO2",
            "tagName": "定制化属性2",
            "group": "5",
            "groupTitle": "定制化管理",
            "tagType": "input",
            "dimCode": "",
            "fieldName": "",
            "fieldType": "",
            "isShow": "true",
            "sort": "1",
            "label": "定制化属性2",
            "editer": "input",
            "value": "EXT_PRO2",
            "placeholder": "定制化属性2"
        }]
    }],
    "extData": {
        "VERSEQ": "V1.0",
        "DATA_UNITCn": "",
        "REL_DEPTCn": "",
        "AUTH_SYSTEMCn": "",
        "EN_NAME": "t",
        "DATA_VAL_AREA": "t",
        "EXT_PRO1": "t",
        "EXT_PRO2": "t",
        "DATA_TYPECn": "日期时间类",
        "DATA_TYPE": "日期时间类",
        "STD_CODE": "t",
        "TOPIC_PATH": "t",
        "CN_NAME": "t"
    }
}